### ISSUE TITLE
Client Error

### ISSUE THREAD

**Issue by elliottstorey** [sspathak/VoiceChat#4]
I ran pythonserver.py and it appears to work no problem, binding to 0.0.0.0:9001. However, when I run pythonclient.py I get this error:

File "C:\Python\VC\VoiceChat\pythonclient.py", line 283, in connect
    s.connect((SERVER_IP, SERVER_PORT))
OSError: [WinError 10049] The requested address is not valid in its context

I do not think this is a device error. Do you have any ideas for a fix?

**Comment by sspathak** [comment]
Hi, it seems like the client isn't accepting the IP address under `SERVER_IP`. If you are running both the server and the client on your local machine, this address should be either `"0.0.0.0"` or `"127.0.0.1"` or `"localhost"`. I recommend trying all these options.

NOTE: You may have to allow Windows firewall access (in case you are prompted).

**Comment by elliottstorey** [comment]
Thank you!
