### ISSUE TITLE
Stuttering audio still persists

### ISSUE THREAD

**Issue by tiagorribeiro24** [sspathak/VoiceChat#7]
Hello. Thank you for the previous fix, but I'm still having stuttering audio when sleep is used. Without it, now it doesn't crash on the CBC but does very weird sounding, like robotic/high pitch sounds. Plus it also stutters a bit. It's barely understandable what is said. I'm thinking that maybe is just happening to me?

**Comment by sspathak** [comment]
I ran a quick test on GCP with an f1-micro instance and it seems to be working fine on that. I noticed a stuttering issue when using a high `TX_BATCH_SIZE` so I pushed an update to main directly with values that worked for me. You could try lowering it further and also try reducing the `SHARED_BUF_SIZE`

**Comment by tiagorribeiro24** [comment]
I experimented with those variables and lowering them didn't helped me at all. But raising them it did stoped the stuttering but it has some weird pauses every like 1 or so seconds. Only when I raised by a lot it seems to work fine on localhost. But when I tested on ms azure machines it does some weird bugs (sometimes stops working after sound glitching out or sometimes the sound gets very delayed).

**Comment by tiagorribeiro24** [comment]
Can you tell me which python and packages versions you running the app?
Also, which OS you using it on?

**Comment by sspathak** [comment]
Here's my `pip freeze` output with the packages and versions:
```
cffi==1.16.0
numpy==1.21.6
pycparser==2.21
pycryptodome==3.10.4
sounddevice==0.4.6
```

In addition, I have uploaded a video on YouTube where I walk through how I set up my GCP VM. [link](https://www.youtube.com/watch?v=EIVwWbLopVw)

Server:
GCP Compute Engine N1 series F1-micro, 1vCPU, 614MB RAM
Ubuntu 20.04 LTS

Client:
Apple MacBook Air M2, 8GB
macOS 13.6

**Comment by tiagorribeiro24** [comment]
Well for some reason it works now 😅😅 idk what it was, probably some outdated version or something.
Thank you so much ❤️

**Comment by tiagorribeiro24** [comment]
One thing that I think it would be worth it to have is the remove of a client on the server, when the client itself closes the window without having a connection.
For example, client A wants to speak with client B, he inserts it and waits for the client B to do the same. But client B doesn't and client A ends up closing the window because ctrl+c or other input doesn't work since it's stuck on a blocking socket receive() function. If the clients A does that again and again, it keeps stacking "waiting..." connections on to the server.
When client B finally wants to connect, the connection fails saying that the connection was canceled. Here's the error that happened to me:

> message length = 512
***** STARTING RECORD TRANSMIT THREAD *****
***** STARTING RECEIVE PLAY THREAD *****
press enter to exitException in thread Thread-4 (transmitter_consumer):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "threading.py", line 989, in run
  File "pythonclient.py", line 225, in transmitter_consumer
Exception in thread Thread-5 (receiver_producer):
Traceback (most recent call last):
  File "threading.py", line 1052, in _bootstrap_inner
  File "pythonclient.py", line 188, in transmit
  File "threading.py", line 989, in run
  File "pythonclient.py", line 92, in split_send_bytes
  File "pythonclient.py", line 279, in receiver_producer
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
  File "pythonclient.py", line 253, in receive
  File "pythonclient.py", line 107, in split_recv_bytes
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine

It would be nice to catch the signal of exiting a window and/or a message is sent to the server so the server knows that client A is no longer active.

**Comment by sspathak** [comment]
Thanks for the feedback! I agree the way clients disconnect from the server needs to be improved. I might implement your suggestion in the next update.
